### ISSUE TITLE
 项目导入问题

### ISSUE THREAD

**Issue by HuaRongSAO** [HiKumho/Go#1]
我在android studio导入这个项目，怎么都无编译成功。  因为这是个eclipse的安卓项目？

**Comment by jinhucheung** [comment]
谢谢反馈，我之后会推送 android studio 的版本

**Comment by jinhucheung** [comment]
你好， android studio 的版本可查看 项目分支 [android-studio](https://github.com/HiKumho/Go/tree/android-studio)， 希望能帮到你
